const Ranking = require("./ranking.model"),
	Food = require("./food.model"),
	FoodType = require("./food_type.model"),
	Order = require("./order.model"),
	OrderDetail = require("./order_detail.model"),
	SessionStore = require("./session_store.model"),
	Notification = require("./notification.model"),
	Voucher = require("./voucher.model"),
	Address = require("./address.model"),
	User = require("./user.model"),
	VirtualDisplayVoucher = require("./virtual_display_voucher.model"),
	Branch = require("./branch.model");

module.exports = {
	Ranking,
	Food,
	FoodType,
	Order,
	OrderDetail,
	SessionStore,
	Notification,
	Voucher,
	Address,
	User,
	VirtualDisplayVoucher,
	Branch,
};
